const {chromium}=require('playwright');const path=require('path'),assert=require('node:assert/strict'),fs=require('fs');
process.chdir(path.join(__dirname,'..'));fs.mkdirSync('test-results',{recursive:true});
(async()=>{const browser=await chromium.launch();const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.clock.install();await page.goto('file://'+path.resolve('锅盖雪人.html'));const snap=()=>page.evaluate(()=>skySnowSnapshot());let held=new Set();async function setKeys(want){const next=new Set(want);for(const k of held)if(!next.has(k))await page.keyboard.up(k);for(const k of next)if(!held.has(k))await page.keyboard.down(k);held=next}const result=[];
for(let level=0;level<3;level++){if(level)await page.click('#home');await page.click(`[data-level="${level}"]`);await page.click('#start');let initial=await snap();assert.equal(initial.level,level);const visited=new Set();let state;for(let i=0;i<2200;i++){state=await snap();visited.add(state.room);if(state.mode!=='play')break;const p=state.player,desired=['j'];if(state.clear){if(p.x<905)desired.push('d');if(p.y<375)desired.push('s');if(p.y>407)desired.push('w')}else{let e=[...state.enemies].sort((a,b)=>Math.hypot(a.x-p.x,a.y-p.y)-Math.hypot(b.x-p.x,b.y-p.y))[0];if(e){const dx=e.x-p.x,dy=e.y-p.y;if(Math.abs(dx)>63)desired.push(dx>0?'d':'a');else if(dx*p.face<0)desired.push(dx>0?'d':'a');if(Math.abs(dy)>13)desired.push(dy>0?'s':'w');await setKeys(desired);if(p.z===0&&p.cd.jump===0)await page.keyboard.press('k');if(Math.abs(dx)<160&&Math.abs(dy)<70&&p.cd.frost===0)await page.keyboard.press('u');if(Math.abs(dy)<30&&dx*p.face>0&&p.cd.lid===0)await page.keyboard.press('l');if(p.hp<115&&p.potions>0)await page.keyboard.press('h')}}await setKeys(desired);await page.clock.runFor(160);if(i%120===0)console.log(`level=${level} room=${state.room} hp=${Math.round(p.hp)} enemies=${state.enemies.length}`)}await setKeys([]);state=await snap();await page.screenshot({path:`test-results/result-${level}.png`});result.push({level,initialEnemyHP:initial.enemies[0].max,mode:state.mode,rooms:[...visited],seconds:state.clock,hp:state.player.hp,kills:state.kills});assert.equal(state.mode,'win',JSON.stringify(result));assert.equal(visited.size,4);await page.click('#retry');assert.equal((await snap()).room,0);await page.keyboard.press('Escape');await page.click('#home');if(level<2){await page.click('#start');await page.keyboard.press('Escape')}}
// Lose without attacking, then restart with keyboard.
await page.click('[data-level="2"]');await page.click('#start');await page.keyboard.down('d');await page.clock.runFor(2100);await page.keyboard.up('d');for(let i=0;i<700;i++){if((await snap()).mode==='lose')break;await page.clock.runFor(250)}assert.equal((await snap()).mode,'lose');await page.screenshot({path:'test-results/lose.png'});await page.keyboard.press('r');assert.equal((await snap()).mode,'play');assert.equal((await snap()).player.hp,160);
// Pause freezes state; blur automatically pauses.
await page.keyboard.press('Escape');const before=await snap();await page.clock.runFor(1000);assert.equal((await snap()).clock,before.clock);await page.click('#resume');await page.evaluate(()=>window.dispatchEvent(new Event('blur')));assert.equal((await snap()).mode,'pause');await page.click('#resume');
for(const viewport of [{width:1280,height:720},{width:1024,height:768},{width:1672,height:941}]){await page.setViewportSize(viewport);await page.screenshot({path:`test-results/desktop-${viewport.width}.png`});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
assert.deepEqual(errors,[]);console.log(JSON.stringify({browser:browser.version(),result,lossRestart:true,pause:true,blur:true,errors},null,2));fs.writeFileSync('test-results/results.json',JSON.stringify({browser:browser.version(),result,lossRestart:true,pause:true,blur:true,errors},null,2));await browser.close()})().catch(e=>{console.error(e);process.exit(1)});
